### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by henriquesouzadev** [josepholiveira/podcastr#2]
Cara me tira uma dúvida? Como foi feito o deploy do json-server na vercel? No meu está dando erro.

**Comment by josepholiveira** [comment]
Fala @henriquesouzadev, tudo bem?

Ele foi feito utilizando o https://my-json-server.typicode.com/ e configurando a URL da api por lá.

Eu apenas precisei configurar o `db.json` para ter menos que 10kb e dá tudo certo :rocket:

**Comment by henriquesouzadev** [comment]
Tudo bem @josepholiveira e você? Desculpa minha ignorância, mas acho que perdi essa parte la na NLW. Onde configura a URL da api? Dentro de um arquivo no Next? Queria colocar meu projeto na Vercel, mas sempre da erro no deploy. Parece que ele tá tentando usar o localhost:3333.

api.ts
`import axios from 'axios';
export const api = axios.create({
   baseURL: process.env.API_URL || 'http://localhost:3333'
});`

.env.example
`API_URL=`

**Comment by josepholiveira** [comment]
Opa @henriquesouzadev !

Isso não foi configurado na NLW mesmo, eu fiz por conta própria. 

Basta configurar a baseURL como você configurou mesmo e configurar as variáveis ambiente lá na vercel e rodar o deploy novamente :rocket:

**Comment by henriquesouzadev** [comment]
Ah sim! Estou tentando há algum tempo mas sem muita evolução. Tem alguma explicação na internet ou você fez tudo via documentação?

**Comment by josepholiveira** [comment]
Opa @henriquesouzadev , beleza?

Eu não tenho nenhuma documentação específica pra isso, apenas utilizei aquela API mesmo que enviei, e configurei nas environment variables da vercel essa variável `API_URL` com o seguinte valor: `https://my-json-server.typicode.com/josepholiveira/podcastr`

**Comment by henriquesouzadev** [comment]
@josepholiveira Beleza! Fiz várias tentativas ontem e estava quase desistindo, quando acabei percebendo essa solução que você me passou agora. Aí o deploy funcionou certinho. Obrigado pelo seu tempo e pelas respostas! Forte abraço!! 😀

**Comment by josepholiveira** [comment]
Opa @henriquesouzadev, por nada! Fico feliz que ajudou :rocket:
